### ISSUE TITLE
Hard-Coded Secret in secret_test.go

### ISSUE THREAD

**Issue by tylerezimmerman** [DelineaXPM/tss-sdk-go#14]
There is a hard-coded secret in https://github.com/DelineaXPM/tss-sdk-go/blob/main/server/secret_test.go

![image](https://user-images.githubusercontent.com/100804646/191832808-a68293f3-a306-49dc-915f-851b2706fb7a.png)

**Comment by delineaKrehl** [comment]
This is test collateral only. The actual connection are made with secrets set in the pipeline.
