### ISSUE TITLE
Getting Login failed

### ISSUE THREAD

**Issue by tibco-postman** [DelineaXPM/tss-sdk-go#28]
**Description of the issue**

I have setup an application account in Secret Server, and I have verified that it works by trying the Windows TSS SDK client.
Now, when I'm trying with the Go SDK, setting TSS_USERNAME to my application account name and having tried with TSS_PASSWORD set to either the SDK key or the application account's password and passing in a secret to retrieve - I get "Login failed".

Obviously, I missing something fundamental here, but I fail to understand what.
With the Windows TSS SDK client, you initialize the SDK with the URL, key and role, but I don't see anything equivalent in the Go SDK?

**Comment by tibco-postman** [comment]
Forgot to mention that in the Go SDK, I have also set the TSS_TENANT to a valid value

**Comment by tibco-postman** [comment]
TLD is com, so not setting that.
Tenant is cloudsg (full URL https://cloudsg.secretservercloud.com/)

What value should be used for TSS_PASSWORD? SDK key?

**Comment by pacificcode** [comment]
TSS_PASSWORD=ActualAccountPassword
To debug if needed, navigate to https://cloudsg.secretservercloud.com/, select "Local Login" and enter the username/password you are using with the tss-sdk-go API calls.

**Comment by pacificcode** [comment]
Im not familiar enough with the windows sdk to advise. The go sdk does not require initialization.

**Comment by delinea-sagar** [comment]
@tibco-postman Can you try to get token using your application account username and password through postman first. You can refer secret server rest API guide for this https://cloudsg.secretservercloud.com/RestApiDocs.ashx?doc=oauth-help.

**Comment by tibco-postman** [comment]
I've verified that Webservices is enabled, but still get "Login Failed".
Tried using Postman, same result:

![image](https://github.com/DelineaXPM/tss-sdk-go/assets/70329335/184ca08a-86df-41eb-938c-7b3b3a018619)

**Comment by tibco-postman** [comment]
I managed to get the Postman call to work. What was needed was to add the parameter `domain` to the call.
Adding that to the Credentials var made things work!

Thanks for help!
